export { z } from 'zod';
export type { ZodType } from 'zod';

export {
  CURSOR_CLICK_DURATION_MS,
  CURSOR_CONNECTION_IDLE_TIMEOUT_MS,
  CURSOR_EVENTS,
  CURSOR_IDLE_TIMEOUT_MS,
  CURSOR_MOVE_FPS,
  CURSOR_MOVE_INTERVAL_MS,
  cursorBatchSchema,
  type CursorBatch,
  cursorColorInputSchema,
  type CursorColorInput,
  cursorDisconnectNoticeSchema,
  type CursorDisconnectNotice,
  cursorInputSchema,
  type CursorInput,
  cursorPositionSchema,
  type CursorPosition,
  cursorRemovalSchema,
  type CursorRemoval,
  cursorRoomIdSchema,
  type CursorRoomId,
  cursorSessionSchema,
  type CursorSession,
  cursorSocketAuthSchema,
  type CursorSocketAuth,
  cursorUsernameSchema,
  type CursorUsername,
  cursorUpdateSchema,
  type CursorUpdate,
  cursorUserSchema,
  type CursorUser,
  ClientToServerEvents,
  ServerToClientEvents,
  DEFAULT_CURSOR_ROOM_ID,
  remoteCursorSchema,
  type RemoteCursor,
} from './cursor/index.js';
export { hexColorSchema, type HexColor } from './schemas/color.js';
