import { CURSOR_CONNECTION_IDLE_TIMEOUT_MS } from '@app/shared';

export const DEFAULT_ALLOWED_ORIGINS = [
  'http://localhost:5173',
  'http://127.0.0.1:5173',
] as const;

export const DEFAULT_CURSOR_MAX_CONNECTIONS_PER_IP = 20;
export const DEFAULT_CURSOR_MAX_PARTICIPANTS_PER_ROOM = 100;
export const DEFAULT_CURSOR_MAX_TOTAL_CONNECTIONS = 1_000;
export const DEFAULT_SOCKET_MAX_HTTP_BUFFER_BYTES = 4_096;
export const DEFAULT_CURSOR_CONNECTION_IDLE_TIMEOUT_MS =
  CURSOR_CONNECTION_IDLE_TIMEOUT_MS;
